from prefect import task, get_run_logger
import pandas as pd
import uuid
from pathlib import Path
from config.settings import SQLSERVER_CONN_BC

# Chemin absolu vers le dossier data_lake dans prefect_ods
DATA_LAKE_PATH = Path(__file__).parent.parent.parent / 'data_lake'

@task(name="Extract Sales_Line", retries=3, retry_delay_seconds=10)
def extract_sales_line():
    logger = get_run_logger()
    
    query = """
    SELECT 
    [Document Type] [DocumentType],
    [Document No_] [DocumentNo],
    [Line No_] [LineNo],
    [Sell-to Customer No_] [SelltoCustomerNo],
    [Type] [Type],
    [No_] [No],
    [Location Code] [LocationCode],
    [Posting Group] [PostingGroup],
    [Shipment Date] [ShipmentDate],
    [Description] [Description],
    [Description 2] [Description2],
    [Unit of Measure] [UnitofMeasure],
    [Quantity] [Quantity],
    [Outstanding Quantity] [OutstandingQuantity],
    [Qty_ to Invoice] [QtyToInvoice],
    [Qty_ to Ship] [QtyToShip],
    [Unit Price] [UnitPrice],
    [Unit Cost (LCY)] [UnitCostLCY],
    [VAT _] [VAT],
    [Line Discount _] [LineDiscountPercent],
    [Line Discount Amount] [LineDiscountAmount],
    [Amount] [Amount],
    [Amount Including VAT] [AmountIncludingVAT],
    [Allow Invoice Disc_] [AllowInvoiceDisc],
    [Gross Weight] [GrossWeight],
    [Net Weight] [NetWeight],
    [Units per Parcel] [UnitsPerParcel],
    [Unit Volume] [UnitVolume],
    [Appl_-to Item Entry] [ApplToItemEntry],
    [Shortcut Dimension 1 Code] [ShortcutDimension1Code],
    [Shortcut Dimension 2 Code] [ShortcutDimension2Code],
    [Customer Price Group] [CustomerPriceGroup],
    [Job No_] [JobNo],
    [Work Type Code] [WorkTypeCode],
    [Recalculate Invoice Disc_] [RecalculateInvoiceDisc],
    [Outstanding Amount] [OutstandingAmount],
    [Qty_ Shipped Not Invoiced] [QtyShippedNotInvoiced],
    [Shipped Not Invoiced] [ShippedNotInvoiced],
    [Quantity Shipped] [QuantityShipped],
    [Quantity Invoiced] [QuantityInvoiced],
    [Shipment No_] [ShipmentNo],
    [Shipment Line No_] [ShipmentLineNo],
    [Profit _] [Profit],
    [Bill-to Customer No_] [BilltoCustomerNo],
    [Inv_ Discount Amount] [InvDiscountAmount],
    [Purchase Order No_] [PurchaseOrderNo],
    [Purch_ Order Line No_] [PurchaseOrderLineNo],
    [Drop Shipment] [DropShipment],
    [Gen_ Bus_ Posting Group] [GenBusPostingGroup],
    [Gen_ Prod_ Posting Group] [GenProdPostingGroup],
    [VAT Calculation Type] [VATCalculationType],
    [Transaction Type] [TransactionType],
    [Transport Method] [TransportMethod],
    [Attached to Line No_] [AttachedtoLineNo],
    [Exit Point] [ExitPoint],
    [Area] [Area],
    [Transaction Specification] [TransactionSpecification],
    [Tax Category] [TaxCategory],
    [Tax Area Code] [TaxAreaCode],
    [Tax Liable] [TaxLiable],
    [Tax Group Code] [TaxGroupCode],
    [VAT Clause Code] [VATClauseCode],
    [VAT Bus_ Posting Group] [VATBusPostingGroup],
    [VAT Prod_ Posting Group] [VATProdPostingGroup],
    [Currency Code] [CurrencyCode],
    [Outstanding Amount (LCY)] [OutstandingAmountLCY],
    [Shipped Not Invoiced (LCY)] [ShippedNotInvoicedLCY],
    [Shipped Not Inv_ (LCY) No VAT] [ShippedNotInvLCYNoVAT],
    [Reserve] [Reserve],
    [Blanket Order No_] [BlanketOrderNo],
    [Blanket Order Line No_] [BlanketOrderLineNo],
    [VAT Base Amount] [VATBaseAmount],
    [Unit Cost] [UnitCost],
    [System-Created Entry] [SystemCreatedEntry],
    [Line Amount] [LineAmount],
    [VAT Difference] [VATDifference],
    [Inv_ Disc_ Amount to Invoice] [InvDiscountAmountToInvoice],
    [VAT Identifier] [VATIdentifier],
    [IC Partner Ref_ Type] [ICPartnerRefType],
    [IC Partner Reference] [ICPartnerReference],
    [Prepayment _] [Prepayment],
    [Prepmt_ Line Amount] [PrepmtLineAmount],
    [Prepmt_ Amt_ Inv_] [PrepmtAmtInv],
    [Prepmt_ Amt_ Incl_ VAT] [PrepmtAmtInclVAT],
    [Prepayment Amount] [PrepaymentAmount],
    [Prepmt_ VAT Base Amt_] [PrepmtVATBaseAmount],
    [Prepayment VAT _] [PrepaymentVAT],
    [Prepmt_ VAT Calc_ Type] [PrepmtVATCalcType],
    [Prepayment VAT Identifier] [PrepaymentVATIdentifier],
    [Prepayment Tax Area Code] [PrepaymentTaxAreaCode],
    [Prepayment Tax Liable] [PrepaymentTaxLiable],
    [Prepayment Tax Group Code] [PrepaymentTaxGroupCode],
    [Prepmt Amt to Deduct] [PrepmtAmtToDeduct],
    [Prepmt Amt Deducted] [PrepmtAmtDeducted],
    [Prepayment Line] [PrepaymentLine],
    [Prepmt_ Amount Inv_ Incl_ VAT] [PrepmtAmountInvInclVAT],
    [Prepmt_ Amount Inv_ (LCY)] [PrepmtAmountInvLCY],
    [IC Partner Code] [ICPartnerCode],
    [Prepmt_ VAT Amount Inv_ (LCY)] [PrepmtVATAmountInvLCY],
    [Prepayment VAT Difference] [PrepaymentVATDifference],
    [Prepmt VAT Diff_ to Deduct] [PrepmtVATDiffToDeduct],
    [Prepmt VAT Diff_ Deducted] [PrepmtVATDiffDeducted],
    [Pmt_ Discount Amount] [PmtDiscountAmount],
    [Line Discount Calculation] [LineDiscountCalculation],
    [Dimension Set ID] [DimensionSetID],
    [Qty_ to Assemble to Order] [QtyToAssembleToOrder],
    [Qty_ to Asm_ to Order (Base)] [QtyToAsmToOrderBase],
    [Job Task No_] [JobTaskNo],
    [Job Contract Entry No_] [JobContractEntryNo],
    [Deferral Code] [DeferralCode],
    [Returns Deferral Start Date] [ReturnsDeferralStartDate],
    [Variant Code] [VariantCode],
    [Bin Code] [BinCode],
    [Qty_ per Unit of Measure] [QtyPerUnitofMeasure],
    [Planned] [Planned],
    [Unit of Measure Code] [UnitofMeasureCode],
    [Quantity (Base)] [QuantityBase],
    [Outstanding Qty_ (Base)] [OutstandingQtyBase],
    [Qty_ to Invoice (Base)] [QtyToInvoiceBase],
    [Qty_ to Ship (Base)] [QtyToShipBase],
    [Qty_ Shipped Not Invd_ (Base)] [QtyShippedNotInvdBase],
    [Qty_ Shipped (Base)] [QtyShippedBase],
    [Qty_ Invoiced (Base)] [QtyInvoicedBase],
    [FA Posting Date] [FAPostingDate],
    [Depreciation Book Code] [DepreciationBookCode],
    [Depr_ until FA Posting Date] [DeprUntilFAPostingDate],
    [Duplicate in Depreciation Book] [DuplicateinDepreciationBook],
    [Use Duplication List] [UseDuplicationList],
    [Responsibility Center] [ResponsibilityCenter],
    [Out-of-Stock Substitution] [OutOfStockSubstitution],
    [Originally Ordered No_] [OriginallyOrderedNo],
    [Originally Ordered Var_ Code] [OriginallyOrderedVarCode],
    [Cross-Reference No_] [CrossReferenceNo],
    [Unit of Measure (Cross Ref_)] [UnitofMeasureCrossRef],
    [Cross-Reference Type] [CrossReferenceType],
    [Cross-Reference Type No_] [CrossReferenceTypeNo],
    [Item Category Code] [ItemCategoryCode],
    [Nonstock] [Nonstock],
    [Purchasing Code] [PurchasingCode],
    [Product Group Code] [ProductGroupCode],
    [Special Order] [SpecialOrder],
    [Special Order Purchase No_] [SpecialOrderPurchaseNo],
    [Special Order Purch_ Line No_] [SpecialOrderPurchLineNo],
    [Completely Shipped] [CompletelyShipped],
    [Requested Delivery Date] [RequestedDeliveryDate],
    [Promised Delivery Date] [PromisedDeliveryDate],
    [Shipping Time] [ShippingTime],
    [Outbound Whse_ Handling Time] [OutboundWhseHandlingTime],
    [Planned Delivery Date] [PlannedDeliveryDate],
    [Planned Shipment Date] [PlannedShipmentDate],
    [Shipping Agent Code] [ShippingAgentCode],
    [Shipping Agent Service Code] [ShippingAgentServiceCode],
    [Allow Item Charge Assignment] [AllowItemChargeAssignment],
    [Return Qty_ to Receive] [ReturnQtyToReceive],
    [Return Qty_ to Receive (Base)] [ReturnQtyToReceiveBase],
    [Return Qty_ Rcd_ Not Invd_] [ReturnQtyRcdNotInvd],
    [Ret_ Qty_ Rcd_ Not Invd_(Base)] [RetQtyRcdNotInvdBase],
    [Return Rcd_ Not Invd_] [ReturnRcdNotInvd],
    [Return Rcd_ Not Invd_ (LCY)] [ReturnRcdNotInvdLCY],
    [Return Qty_ Received] [ReturnQtyReceived],
    [Return Qty_ Received (Base)] [ReturnQtyReceivedBase],
    [Appl_-from Item Entry] [ApplFromItemEntry],
    [BOM Item No_] [BOMItemNo],
    [Return Receipt No_] [ReturnReceiptNo],
    [Return Receipt Line No_] [ReturnReceiptLineNo],
    [Return Reason Code] [ReturnReasonCode],
    [Copied From Posted Doc_] [CopiedFromPostedDoc],
    [Allow Line Disc_] [AllowLineDisc],
    [Customer Disc_ Group] [CustomerDiscGroup],
    [Subtype] [Subtype],
    [Price description] [PriceDescription],
    [$systemId] [systemId],
    [$systemCreatedAt] [systemCreatedAt],
    [$systemCreatedBy] [systemCreatedBy],
    [$systemModifiedAt] [systemModifiedAt],
    [$systemModifiedBy] [systemModifiedBy],
    [IC Item Reference No_] [ICItemReferenceNo],
    [Prepmt_ Pmt_ Discount Amount] [PrepmtPmtDiscountAmount],
    [Selected Alloc_ Account No_] [SelectedAllocAccountNo],
    [Allocation Account No_] [AllocationAccountNo],
    [Qty_ Rounding Precision] [QtyRoundingPrecision],
    [Qty_ Rounding Precision (Base)] [QtyRoundingPrecisionBase],
    [Item Reference No_] [ItemReferenceNo],
    [Item Reference Unit of Measure] [ItemReferenceUnitofMeasure],
    [Item Reference Type] [ItemReferenceType],
    [Item Reference Type No_] [ItemReferenceTypeNo],
    [Price Calculation Method] [PriceCalculationMethod]

    FROM [company_name].[dbo].[table_business_central_prefix$Sales Line$id_business_central]
    """
    
    df = pd.read_sql(query, con=SQLSERVER_CONN_BC)
    
    # Convertir les colonnes UUID en string
    for col in df.select_dtypes(include=['object']).columns:
        if df[col].apply(lambda x: isinstance(x, uuid.UUID)).any():
            df[col] = df[col].astype(str)
    
    # Utilisation du chemin absolu pour sauvegarder le fichier parquet
    output_path = DATA_LAKE_PATH / 'raw' / 'sales_line.parquet'
    df.to_parquet(str(output_path))
    logger.info(f"{len(df)} lignes extraites pour Sales_Line.")
    return df
