from prefect import task, get_run_logger
import pandas as pd
import uuid
from pathlib import Path
from config.settings import SQLSERVER_CONN_BC

# Chemin absolu vers le dossier data_lake dans prefect_ods
DATA_LAKE_PATH = Path(__file__).parent.parent.parent / 'data_lake'

@task(name="Extract Sales_Header", retries=3, retry_delay_seconds=10)
def extract_sales_header():
    logger = get_run_logger()
    
    query = """
    select 
       A.[Document Type] [DocumentType]
      ,A.[No_] [No]
      ,[Sell-to Customer No_] [SelltoCustomerNo]
      ,[Bill-to Customer No_] [BilltoCustomerNo]
      ,[Bill-to Name] [BilltoName]
      ,[Bill-to Name 2] [BilltoName2]
      ,[Bill-to Address] [BilltoAddress]
      ,[Bill-to Address 2] [BilltoAddress2]
      ,[Bill-to City] [BilltoCity]
      ,[Bill-to Contact] [BilltoContact]
      ,[Your Reference] [YourReference]
      ,[Ship-to Code] [ShiptoCode]
      ,[Ship-to Name] [ShiptoName]
      ,[Ship-to Name 2] [ShiptoName2]
      ,[Ship-to Address] [ShiptoAddress]
      ,[Ship-to Address 2] [ShiptoAddress2]
      ,[Ship-to City] [ShiptoCity]
      ,[Ship-to Contact] [ShiptoContact]
      ,[Order Date] [OrderDate]
      ,[Posting Date] [PostingDate]
      ,[Shipment Date] [ShipmentDate]
      ,[Posting Description] [PostingDescription]
      ,[Payment Terms Code] [PaymentTermsCode]
      ,[Due Date] [DueDate]
      ,[Payment Discount _] [PaymentDiscountPercent]
      ,[Pmt_ Discount Date] [PmtDiscountDate]
      ,[Shipment Method Code] [ShipmentMethodCode]
      ,[Location Code] [LocationCode]
      ,[Shortcut Dimension 1 Code] [ShortcutDimension1Code]
      ,[Shortcut Dimension 2 Code] [ShortcutDimension2Code]
      ,[Customer Posting Group] [CustomerPostingGroup]
      ,[Currency Code] [CurrencyCode]
      ,[Currency Factor] [CurrencyFactor]
      ,[Customer Price Group] [CustomerPriceGroup]
      ,[Prices Including VAT] [PricesIncludingVAT]
      ,[Invoice Disc_ Code] [InvoiceDiscCode]
      ,[Customer Disc_ Group] [CustomerDiscGroup]
      ,[Language Code] [LanguageCode]
      ,[Salesperson Code] [SalespersonCode]
      ,[Order Class] [OrderClass]
      ,[No_ Printed] [NoPrinted]
      ,[On Hold] [OnHold]
      ,[Applies-to Doc_ Type] [AppliesToDocType]
      ,[Applies-to Doc_ No_] [AppliesToDocNo]
      ,[Bal_ Account No_] [BalAccountNo]
      ,[Ship] [Ship]
      ,[Invoice] [Invoice]
      ,[Print Posted Documents] [PrintPostedDocuments]
      ,[Shipping No_] [ShippingNo]
      ,[Posting No_] [PostingNo]
      ,[Last Shipping No_] [LastShippingNo]
      ,[Last Posting No_] [LastPostingNo]
      ,[Prepayment No_] [PrepaymentNo]
      ,[Last Prepayment No_] [LastPrepaymentNo]
      ,[Prepmt_ Cr_ Memo No_] [PrepmtCrMemoNo]
      ,[Last Prepmt_ Cr_ Memo No_] [LastPrepmtCrMemoNo]
      ,[VAT Registration No_] [VATRegistrationNo]
      ,[Combine Shipments] [CombineShipments]
      ,[Reason Code] [ReasonCode]
      ,[Gen_ Bus_ Posting Group] [GenBusPostingGroup]
      ,[EU 3-Party Trade] [EU3PartyTrade]
      ,[Transaction Type] [TransactionType]
      ,[Transport Method] [TransportMethod]
      ,[VAT Country_Region Code] [VATCountryRegionCode]
      ,[Sell-to Customer Name] [SelltoCustomerName]
      ,[Sell-to Customer Name 2] [SelltoCustomerName2]
      ,[Sell-to Address] [SelltoAddress]
      ,[Sell-to Address 2] [SelltoAddress2]
      ,[Sell-to City] [SelltoCity]
      ,[Sell-to Contact] [SelltoContact]
      ,[Bill-to Post Code] [BilltoPostCode]
      ,[Bill-to County] [BilltoCounty]
      ,[Bill-to Country_Region Code] [BilltoCountryRegionCode]
      ,[Sell-to Post Code] [SelltoPostCode]
      ,[Sell-to County] [SelltoCounty]
      ,[Sell-to Country_Region Code] [SelltoCountryRegionCode]
      ,[Ship-to Post Code] [ShiptoPostCode]
      ,[Ship-to County] [ShiptoCounty]
      ,[Ship-to Country_Region Code] [ShiptoCountryRegionCode] 
      ,[Bal_ Account Type] [BalAccountType]
      ,[Exit Point] [ExitPoint]
      ,[Correction] [Correction]
      ,[Document Date] [DocumentDate]
      ,[External Document No_] [ExternalDocumentNo]
      ,[Area] [Area]
      ,[Transaction Specification] [TransactionSpecification]
      ,[Payment Method Code] [PaymentMethodCode]
      ,[Shipping Agent Code] [ShippingAgentCode]
      ,[Package Tracking No_] [PackageTrackingNo]
      ,[No_ Series] [NoSeries]
      ,[Posting No_ Series] [PostingNoSeries]
      ,[Shipping No_ Series] [ShippingNoSeries]
      ,[Tax Area Code] [TaxAreaCode]
      ,[Tax Liable] [TaxLiable]
      ,[VAT Bus_ Posting Group] [VATBusPostingGroup]
      ,[Reserve] [Reserve]
      ,[Applies-to ID] [AppliesToID]
      ,[VAT Base Discount _] [VATBaseDiscountPercent]
      ,[Status] [Status]
      ,[Invoice Discount Calculation] [InvoiceDiscountCalculation]
      ,[Invoice Discount Value] [InvoiceDiscountValue]
      ,[Send IC Document] [SendICDocument]
      ,[IC Status] [ICStatus]
      ,[Sell-to IC Partner Code] [SelltoICPartnerCode]
      ,[Bill-to IC Partner Code] [BilltoICPartnerCode]
      ,[IC Direction] [ICDirection]
      ,[Prepayment _] [Prepayment]
      ,[Prepayment No_ Series] [PrepaymentNoSeries]
      ,[Compress Prepayment] [CompressPrepayment]
      ,[Prepayment Due Date] [PrepaymentDueDate]
      ,[Prepmt_ Cr_ Memo No_ Series] [PrepmtCrMemoNoSeries]
      ,[Prepmt_ Posting Description] [PrepmtPostingDescription]
      ,[Prepmt_ Pmt_ Discount Date] [PrepmtPmtDiscountDate]
      ,[Prepmt_ Payment Terms Code] [PrepmtPaymentTermsCode]
      ,[Prepmt_ Payment Discount _] [PrepmtPaymentDiscountPercent]
      ,[Quote No_] [QuoteNo]
      ,[Quote Valid Until Date] [QuoteValidUntilDate]
      ,[Quote Sent to Customer] [QuoteSentToCustomer]
      ,[Quote Accepted] [QuoteAccepted]
      ,[Quote Accepted Date] [QuoteAcceptedDate]
      ,[Job Queue Status] [JobQueueStatus]
      ,[Job Queue Entry ID] [JobQueueEntryID]
      ,[Incoming Document Entry No_] [IncomingDocumentEntryNo]
      ,[IsTest] [IsTest]
      ,[Sell-to Phone No_] [SelltoPhoneNo]
      ,[Sell-to E-Mail] [SelltoEmail]
      ,[Payment Instructions Id] [PaymentInstructionsId]
      ,[Work Description] [WorkDescription]
      ,[Dimension Set ID] [DimensionSetID]
      ,[Payment Service Set ID] [PaymentServiceSetID]
      ,[Direct Debit Mandate ID] [DirectDebitMandateID]
      ,[Doc_ No_ Occurrence] [DocNoOccurrence]
      ,[Campaign No_] [CampaignNo]
      ,[Sell-to Customer Template Code] [SelltoCustomerTemplateCode]
      ,[Sell-to Contact No_] [SelltoContactNo]
      ,[Bill-to Contact No_] [BilltoContactNo]
      ,[Bill-to Customer Template Code] [BilltoCustomerTemplateCode]
      ,[Opportunity No_] [OpportunityNo]
      ,[Responsibility Center] [ResponsibilityCenter]
      ,[Shipping Advice] [ShippingAdvice]
      ,[Posting from Whse_ Ref_] [PostingFromWhseRef]
      ,[Requested Delivery Date] [RequestedDeliveryDate]
      ,[Promised Delivery Date] [PromisedDeliveryDate]
      ,[Shipping Time] [ShippingTime]
      ,[Outbound Whse_ Handling Time] [OutboundWhseHandlingTime]
      ,[Shipping Agent Service Code] [ShippingAgentServiceCode]
      ,[Receive] [Receive]
      ,[Return Receipt No_] [ReturnReceiptNo]
      ,[Return Receipt No_ Series] [ReturnReceiptNoSeries]
      ,[Last Return Receipt No_] [LastReturnReceiptNo]
      ,[Allow Line Disc_] [AllowLineDisc]
      ,[Get Shipment Used] [GetShipmentUsed]
      ,[Id] [Id]
      ,[Assigned User ID] [AssignedUserID]
      ,[$systemId] [systemId]
      ,[ACY Created By$df74057f-5b58-4d6f-8a52-989845f6320c] [ACYCreatedBy]
    FROM [company_name].[dbo].[PE$Sales Header$id_business_central] A
    INNER JOIN [company_name].[dbo].[PE$Sales Header$id_business_central$ext] B
    ON A.[No_] = B.[No_]
    """
    
    df = pd.read_sql(query, con=SQLSERVER_CONN_BC)
    
    # Convertir les colonnes UUID en string
    for col in df.select_dtypes(include=['object']).columns:
        if df[col].apply(lambda x: isinstance(x, uuid.UUID)).any():
            df[col] = df[col].astype(str)
    
    # Utilisation du chemin absolu pour sauvegarder le fichier parquet
    output_path = DATA_LAKE_PATH / 'raw' / 'sales_header.parquet'
    df.to_parquet(str(output_path))
    logger.info(f"{len(df)} lignes extraites pour Sales_Header.")
    return df
