USE [ODS_SERVER]
GO

/****** Object:  Table [dbo].[Sales_Line]    Script Date: 17/07/2025 15:27:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales_Line](
	[DocumentType] [int] NULL,
	[DocumentNo] [nvarchar](20) NULL,
	[LineNo] [int] NULL,
	[SelltoCustomerNo] [nvarchar](20) NULL,
	[Type] [int] NULL,
	[No] [nvarchar](20) NULL,
	[LocationCode] [nvarchar](10) NULL,
	[PostingGroup] [nvarchar](20) NULL,
	[ShipmentDate] [datetime] NULL,
	[Description] [nvarchar](100) NULL,
	[Description2] [nvarchar](50) NULL,
	[UnitofMeasure] [nvarchar](50) NULL,
	[Quantity] [numeric](38, 20) NULL,
	[UnitPrice] [numeric](38, 20) NULL,
	[UnitCostLCY] [numeric](38, 20) NULL,
	[VAT] [numeric](38, 20) NULL,
	[LineDiscountPercent] [numeric](38, 20) NULL,
	[LineDiscountAmount] [numeric](38, 20) NULL,
	[Amount] [numeric](38, 20) NULL,
	[AmountIncludingVAT] [numeric](38, 20) NULL,
	[AllowInvoiceDisc] [tinyint] NULL,
	[GrossWeight] [numeric](38, 20) NULL,
	[NetWeight] [numeric](38, 20) NULL,
	[UnitsPerParcel] [numeric](38, 20) NULL,
	[UnitVolume] [numeric](38, 20) NULL,
	[ApplToItemEntry] [int] NULL,
	[ShortcutDimension1Code] [nvarchar](20) NULL,
	[ShortcutDimension2Code] [nvarchar](20) NULL,
	[CustomerPriceGroup] [nvarchar](10) NULL,
	[JobNo] [nvarchar](20) NULL,
	[WorkTypeCode] [nvarchar](10) NULL,
	[ShipmentNo] [nvarchar](20) NULL,
	[ShipmentLineNo] [int] NULL,
	[BilltoCustomerNo] [nvarchar](20) NULL,
	[InvDiscountAmount] [numeric](38, 20) NULL,
	[DropShipment] [tinyint] NULL,
	[GenBusPostingGroup] [nvarchar](20) NULL,
	[GenProdPostingGroup] [nvarchar](20) NULL,
	[VATCalculationType] [int] NULL,
	[TransactionType] [nvarchar](10) NULL,
	[TransportMethod] [nvarchar](10) NULL,
	[AttachedtoLineNo] [int] NULL,
	[ExitPoint] [nvarchar](10) NULL,
	[Area] [nvarchar](10) NULL,
	[TransactionSpecification] [nvarchar](10) NULL,
	[TaxCategory] [nvarchar](10) NULL,
	[TaxAreaCode] [nvarchar](20) NULL,
	[TaxLiable] [tinyint] NULL,
	[TaxGroupCode] [nvarchar](20) NULL,
	[VATClauseCode] [nvarchar](20) NULL,
	[VATBusPostingGroup] [nvarchar](20) NULL,
	[VATProdPostingGroup] [nvarchar](20) NULL,
	[BlanketOrderNo] [nvarchar](20) NULL,
	[BlanketOrderLineNo] [int] NULL,
	[VATBaseAmount] [numeric](38, 20) NULL,
	[UnitCost] [numeric](38, 20) NULL,
	[SystemCreatedEntry] [tinyint] NULL,
	[LineAmount] [numeric](38, 20) NULL,
	[VATDifference] [numeric](38, 20) NULL,
	[VATIdentifier] [nvarchar](20) NULL,
	[ICPartnerRefType] [int] NULL,
	[ICPartnerReference] [nvarchar](20) NULL,
	[PrepaymentLine] [tinyint] NULL,
	[ICPartnerCode] [nvarchar](20) NULL,
	[PmtDiscountAmount] [numeric](38, 20) NULL,
	[LineDiscountCalculation] [int] NULL,
	[DimensionSetID] [int] NULL,
	[JobTaskNo] [nvarchar](20) NULL,
	[JobContractEntryNo] [int] NULL,
	[DeferralCode] [nvarchar](10) NULL,
	[VariantCode] [nvarchar](10) NULL,
	[BinCode] [nvarchar](20) NULL,
	[QtyPerUnitofMeasure] [numeric](38, 20) NULL,
	[UnitofMeasureCode] [nvarchar](10) NULL,
	[QuantityBase] [numeric](38, 20) NULL,
	[FAPostingDate] [datetime] NULL,
	[DepreciationBookCode] [nvarchar](10) NULL,
	[DeprUntilFAPostingDate] [tinyint] NULL,
	[DuplicateInDepreciationBook] [nvarchar](10) NULL,
	[UseDuplicationList] [tinyint] NULL,
	[ResponsibilityCenter] [nvarchar](10) NULL,
	[CrossReferenceNo] [nvarchar](20) NULL,
	[UnitofMeasureCrossRef] [nvarchar](10) NULL,
	[CrossReferenceType] [int] NULL,
	[CrossReferenceTypeNo] [nvarchar](30) NULL,
	[ItemCategoryCode] [nvarchar](20) NULL,
	[Nonstock] [tinyint] NULL,
	[PurchasingCode] [nvarchar](10) NULL,
	[ProductGroupCode] [nvarchar](10) NULL,
	[ApplFromItemEntry] [int] NULL,
	[ReturnReasonCode] [nvarchar](10) NULL,
	[AllowLineDisc] [tinyint] NULL,
	[CustomerDiscGroup] [nvarchar](20) NULL,
	[PriceDescription] [nvarchar](80) NULL,
	[systemId] [uniqueidentifier] NULL,
	[DocumentType] [int] NULL,
	[OutstandingQuantity] [numeric](38, 20) NULL,
	[QtyToInvoice] [numeric](38, 20) NULL,
	[QtyToShip] [numeric](38, 20) NULL,
	[RecalculateInvoiceDisc] [tinyint] NULL,
	[OutstandingAmount] [numeric](38, 20) NULL,
	[QtyShippedNotInvoiced] [numeric](38, 20) NULL,
	[ShippedNotInvoiced] [numeric](38, 20) NULL,
	[QuantityShipped] [numeric](38, 20) NULL,
	[QuantityInvoiced] [numeric](38, 20) NULL,
	[Profit] [numeric](38, 20) NULL,
	[PurchaseOrderNo] [nvarchar](20) NULL,
	[PurchOrderLineNo] [int] NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[OutstandingAmountLCY] [numeric](38, 20) NULL,
	[ShippedNotInvoicedLCY] [numeric](38, 20) NULL,
	[ShippedNotInvLCYNoVAT] [numeric](38, 20) NULL,
	[Reserve] [int] NULL,
	[InvDiscAmountToInvoice] [numeric](38, 20) NULL,
	[Prepayment] [numeric](38, 20) NULL,
	[PrepmtLineAmount] [numeric](38, 20) NULL,
	[PrepmtAmtInv] [numeric](38, 20) NULL,
	[PrepmtAmtInclVAT] [numeric](38, 20) NULL,
	[PrepaymentAmount] [numeric](38, 20) NULL,
	[PrepmtVATBaseAmt] [numeric](38, 20) NULL,
	[PrepaymentVAT] [numeric](38, 20) NULL,
	[PrepmtVATCalcType] [int] NULL,
	[PrepaymentVATIdentifier] [nvarchar](20) NULL,
	[PrepaymentTaxAreaCode] [nvarchar](20) NULL,
	[PrepaymentTaxLiable] [tinyint] NULL,
	[PrepaymentTaxGroupCode] [nvarchar](20) NULL,
	[PrepmtAmtToDeduct] [numeric](38, 20) NULL,
	[PrepmtAmtDeducted] [numeric](38, 20) NULL,
	[PrepmtAmountInvInclVAT] [numeric](38, 20) NULL,
	[PrepmtAmountInvLCY] [numeric](38, 20) NULL,
	[PrepmtVATAmountInvLCY] [numeric](38, 20) NULL,
	[PrepaymentVATDifference] [numeric](38, 20) NULL,
	[PrepmtVATDiffToDeduct] [numeric](38, 20) NULL,
	[PrepmtVATDiffDeducted] [numeric](38, 20) NULL,
	[QtyToAssembleToOrder] [numeric](38, 20) NULL,
	[QtyToAsmToOrderBase] [numeric](38, 20) NULL,
	[ReturnsDeferralStartDate] [datetime] NULL,
	[Planned] [tinyint] NULL,
	[OutstandingQtyBase] [numeric](38, 20) NULL,
	[QtyToInvoiceBase] [numeric](38, 20) NULL,
	[QtyToShipBase] [numeric](38, 20) NULL,
	[QtyShippedNotInvdBase] [numeric](38, 20) NULL,
	[QtyShippedBase] [numeric](38, 20) NULL,
	[QtyInvoicedBase] [numeric](38, 20) NULL,
	[OutofStockSubstitution] [tinyint] NULL,
	[OriginallyOrderedNo] [nvarchar](20) NULL,
	[OriginallyOrderedVarCode] [nvarchar](10) NULL,
	[SpecialOrder] [tinyint] NULL,
	[SpecialOrderPurchaseNo] [nvarchar](20) NULL,
	[SpecialOrderPurchLineNo] [int] NULL,
	[CompletelyShipped] [tinyint] NULL,
	[RequestedDeliveryDate] [datetime] NULL,
	[PromisedDeliveryDate] [datetime] NULL,
	[ShippingTime] [varchar](32) NULL,
	[OutboundWhseHandlingTime] [varchar](32) NULL,
	[PlannedDeliveryDate] [datetime] NULL,
	[PlannedShipmentDate] [datetime] NULL,
	[ShippingAgentCode] [nvarchar](10) NULL,
	[ShippingAgentServiceCode] [nvarchar](10) NULL,
	[AllowItemChargeAssignment] [tinyint] NULL,
	[ReturnQtyToReceive] [numeric](38, 20) NULL,
	[ReturnQtyToReceiveBase] [numeric](38, 20) NULL,
	[ReturnQtyRcdNotInvd] [numeric](38, 20) NULL,
	[RetQtyRcdNotInvdBase] [numeric](38, 20) NULL,
	[ReturnRcdNotInvd] [numeric](38, 20) NULL,
	[ReturnRcdNotInvdLCY] [numeric](38, 20) NULL,
	[ReturnQtyReceived] [numeric](38, 20) NULL,
	[ReturnQtyReceivedBase] [numeric](38, 20) NULL,
	[BOMItemNo] [nvarchar](20) NULL,
	[ReturnReceiptNo] [nvarchar](20) NULL,
	[ReturnReceiptLineNo] [int] NULL,
	[CopiedFromPostedDoc] [tinyint] NULL,
	[Subtype] [int] NULL
) ON [PRIMARY]
GO


