USE [ODS_SERVER]
GO

/****** Object:  Table [dbo].[Sales_Invoice_Header]    Script Date: 19/07/2025 18:45:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales_Invoice_Header](
	[No] [nvarchar](20) NULL,
	[SelltoCustomerNo] [nvarchar](20) NULL,
	[BilltoCustomerNo] [nvarchar](20) NULL,
	[BilltoName] [nvarchar](100) NULL,
	[BilltoName2] [nvarchar](50) NULL,
	[BilltoAddress] [nvarchar](100) NULL,
	[BilltoAddress2] [nvarchar](50) NULL,
	[BilltoCity] [nvarchar](30) NULL,
	[BilltoContact] [nvarchar](100) NULL,
	[YourReference] [nvarchar](35) NULL,
	[ShiptoCode] [nvarchar](10) NULL,
	[ShiptoName] [nvarchar](100) NULL,
	[ShiptoName2] [nvarchar](50) NULL,
	[ShiptoAddress] [nvarchar](100) NULL,
	[ShiptoAddress2] [nvarchar](50) NULL,
	[ShiptoCity] [nvarchar](30) NULL,
	[ShiptoContact] [nvarchar](100) NULL,
	[OrderDate] [datetime] NULL,
	[PostingDate] [datetime] NULL,
	[ShipmentDate] [datetime] NULL,
	[PostingDescription] [nvarchar](100) NULL,
	[PaymentTermsCode] [nvarchar](10) NULL,
	[DueDate] [datetime] NULL,
	[PaymentDiscountPercent] [numeric](38, 20) NULL,
	[PmtDiscountDate] [datetime] NULL,
	[ShipmentMethodCode] [nvarchar](10) NULL,
	[LocationCode] [nvarchar](10) NULL,
	[ShortcutDimension1Code] [nvarchar](20) NULL,
	[ShortcutDimension2Code] [nvarchar](20) NULL,
	[CustomerPostingGroup] [nvarchar](20) NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[CurrencyFactor] [numeric](38, 20) NULL,
	[CustomerPriceGroup] [nvarchar](10) NULL,
	[PricesIncludingVAT] [tinyint] NULL,
	[InvoiceDiscCode] [nvarchar](20) NULL,
	[CustomerDiscGroup] [nvarchar](20) NULL,
	[LanguageCode] [nvarchar](10) NULL,
	[SalespersonCode] [nvarchar](20) NULL,
	[OrderNo] [nvarchar](20) NULL,
	[NoPrinted] [int] NULL,
	[OnHold] [nvarchar](20) NULL,
	[AppliestoDocType] [int] NULL,
	[AppliestoDocNo] [nvarchar](20) NULL,
	[BalAccountNo] [nvarchar](20) NULL,
	[VATRegistrationNo] [nvarchar](20) NULL,
	[ReasonCode] [nvarchar](10) NULL,
	[GenBusPostingGroup] [nvarchar](20) NULL,
	[EU3PartyTrade] [tinyint] NULL,
	[TransactionType] [nvarchar](10) NULL,
	[TransportMethod] [nvarchar](10) NULL,
	[VATCountryRegionCode] [nvarchar](10) NULL,
	[SelltoCustomerName] [nvarchar](100) NULL,
	[SelltoCustomerName2] [nvarchar](50) NULL,
	[SelltoAddress] [nvarchar](100) NULL,
	[SelltoAddress2] [nvarchar](50) NULL,
	[SelltoCity] [nvarchar](30) NULL,
	[SelltoContact] [nvarchar](100) NULL,
	[BilltoPostCode] [nvarchar](20) NULL,
	[BilltoCounty] [nvarchar](30) NULL,
	[BilltoCountryRegionCode] [nvarchar](10) NULL,
	[SelltoPostCode] [nvarchar](20) NULL,
	[SelltoCounty] [nvarchar](30) NULL,
	[SelltoCountryRegionCode] [nvarchar](10) NULL,
	[ShiptoPostCode] [nvarchar](20) NULL,
	[ShiptoCounty] [nvarchar](30) NULL,
	[ShiptoCountryRegionCode] [nvarchar](10) NULL,
	[BalAccountType] [int] NULL,
	[ExitPoint] [nvarchar](10) NULL,
	[Correction] [tinyint] NULL,
	[DocumentDate] [datetime] NULL,
	[ExternalDocumentNo] [nvarchar](35) NULL,
	[Area] [nvarchar](10) NULL,
	[TransactionSpecification] [nvarchar](10) NULL,
	[PaymentMethodCode] [nvarchar](10) NULL,
	[ShippingAgentCode] [nvarchar](10) NULL,
	[PackageTrackingNo] [nvarchar](30) NULL,
	[PreAssignedNoSeries] [nvarchar](20) NULL,
	[NoSeries] [nvarchar](20) NULL,
	[OrderNoSeries] [nvarchar](20) NULL,
	[PreAssignedNo] [nvarchar](20) NULL,
	[UserID] [nvarchar](50) NULL,
	[SourceCode] [nvarchar](10) NULL,
	[TaxAreaCode] [nvarchar](20) NULL,
	[TaxLiable] [tinyint] NULL,
	[VATBusPostingGroup] [nvarchar](20) NULL,
	[VATBaseDiscountPercent] [numeric](38, 20) NULL,
	[InvoiceDiscountCalculation] [int] NULL,
	[InvoiceDiscountValue] [numeric](38, 20) NULL,
	[PrepaymentNoSeries] [nvarchar](20) NULL,
	[PrepaymentInvoice] [tinyint] NULL,
	[PrepaymentOrderNo] [nvarchar](20) NULL,
	[QuoteNo] [nvarchar](20) NULL,
	[SelltoPhoneNo] [nvarchar](30) NULL,
	[SelltoEmail] [nvarchar](80) NULL,
	[PaymentInstructions] [nvarchar](max) NULL,
	[PaymentInstructionsName] [nvarchar](10) NULL,
	[WorkDescription] [nvarchar](max) NULL,
	[DimensionSetID] [int] NULL,
	[PaymentServiceSetID] [nvarchar](20) NULL,
	[DocumentExchangeIdentifier] [nvarchar](50) NULL,
	[DocumentExchangeStatus] [int] NULL,
	[DocExchOriginalIdentifier] [nvarchar](50) NULL,
	[CoupledtoCRM] [tinyint] NULL,
	[DirectDebitMandateID] [nvarchar](35) NULL,
	[CustLedgerEntryNo] [int] NULL,
	[CampaignNo] [nvarchar](20) NULL,
	[SelltoContactNo] [nvarchar](20) NULL,
	[BilltoContactNo] [nvarchar](20) NULL,
	[OpportunityNo] [nvarchar](20) NULL,
	[ResponsibilityCenter] [nvarchar](10) NULL,
	[AllowLineDisc] [tinyint] NULL,
	[GetShipmentUsed] [tinyint] NULL,
	[ACY Created By] [nvarchar](50) NULL,
	[TM DateTime Created] [datetime] NULL,
	[TM Origing Customer Inv_] [nvarchar](50) NULL,
	[TM PGM ORG] [nvarchar](50) NULL,
	[TM SO Blocked] [tinyint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
