USE [ODS_SERVER]
GO

/****** Object:  Table [dbo].[Sales_CreMemo_Line]    Script Date: 19/07/2025 18:45:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales_CreMemo_Line](
	[DocumentNo] [nvarchar](20) NULL,
	[LineNo] [int] NULL,
	[SelltoCustomerNo] [nvarchar](20) NULL,
	[Type] [int] NULL,
	[No] [nvarchar](20) NULL,
	[LocationCode] [nvarchar](10) NULL,
	[PostingGroup] [nvarchar](20) NULL,
	[ShipmentDate] [datetime] NULL,
	[Description] [nvarchar](100) NULL,
	[Description2] [nvarchar](50) NULL,
	[UnitofMeasure] [nvarchar](10) NULL,
	[Quantity] [numeric](38, 20) NULL,
	[UnitPrice] [numeric](38, 20) NULL,
	[UnitCostLCY] [numeric](38, 20) NULL,
	[VAT] [numeric](38, 20) NULL,
	[LineDiscountPercent] [numeric](38, 20) NULL,
	[LineDiscountAmount] [numeric](38, 20) NULL,
	[Amount] [numeric](38, 20) NULL,
	[AmountIncludingVAT] [numeric](38, 20) NULL,
	[AllowInvoiceDisc] [tinyint] NULL,
	[GrossWeight] [numeric](38, 20) NULL,
	[NetWeight] [numeric](38, 20) NULL,
	[UnitsPerParcel] [numeric](38, 20) NULL,
	[UnitVolume] [numeric](38, 20) NULL,
	[ApplToItemEntry] [int] NULL,
	[ShortcutDimension1Code] [nvarchar](20) NULL,
	[ShortcutDimension2Code] [nvarchar](20) NULL,
	[CustomerPriceGroup] [nvarchar](10) NULL,
	[JobNo] [nvarchar](20) NULL,
	[WorkTypeCode] [nvarchar](10) NULL,
	[OrderNo] [nvarchar](20) NULL,
	[OrderLineNo] [int] NULL,
	[BilltoCustomerNo] [nvarchar](20) NULL,
	[InvDiscountAmount] [numeric](38, 20) NULL,
	[GenBusPostingGroup] [nvarchar](20) NULL,
	[GenProdPostingGroup] [nvarchar](20) NULL,
	[VATCalculationType] [int] NULL,
	[TransactionType] [nvarchar](10) NULL,
	[TransportMethod] [nvarchar](10) NULL,
	[AttachedtoLineNo] [int] NULL,
	[ExitPoint] [nvarchar](10) NULL,
	[Area] [nvarchar](10) NULL,
	[TransactionSpecification] [nvarchar](10) NULL,
	[TaxCategory] [nvarchar](10) NULL,
	[TaxAreaCode] [nvarchar](20) NULL,
	[TaxLiable] [tinyint] NULL,
	[TaxGroupCode] [nvarchar](20) NULL,
	[VATClauseCode] [nvarchar](20) NULL,
	[VATBusPostingGroup] [nvarchar](20) NULL,
	[VATProdPostingGroup] [nvarchar](20) NULL,
	[BlanketOrderNo] [nvarchar](20) NULL,
	[BlanketOrderLineNo] [int] NULL,
	[VATBaseAmount] [numeric](38, 20) NULL,
	[UnitCost] [numeric](38, 20) NULL,
	[SystemCreatedEntry] [tinyint] NULL,
	[LineAmount] [numeric](38, 20) NULL,
	[VATDifference] [numeric](38, 20) NULL,
	[VATIdentifier] [nvarchar](20) NULL,
	[ICPartnerRefType] [int] NULL,
	[ICPartnerReference] [nvarchar](20) NULL,
	[PrepaymentLine] [tinyint] NULL,
	[ICPartnerCode] [nvarchar](20) NULL,
	[PostingDate] [datetime] NULL,
	[PmtDiscountAmount] [numeric](38, 20) NULL,
	[LineDiscountCalculation] [int] NULL,
	[DimensionSetID] [int] NULL,
	[JobTaskNo] [nvarchar](20) NULL,
	[JobContractEntryNo] [int] NULL,
	[DeferralCode] [nvarchar](10) NULL,
	[VariantCode] [nvarchar](10) NULL,
	[BinCode] [nvarchar](20) NULL,
	[QtyPerUnitofMeasure] [numeric](38, 20) NULL,
	[UnitofMeasureCode] [nvarchar](10) NULL,
	[QuantityBase] [numeric](38, 20) NULL,
	[FAPostingDate] [datetime] NULL,
	[DepreciationBookCode] [nvarchar](10) NULL,
	[DeprUntilFAPostingDate] [tinyint] NULL,
	[DuplicateinDepreciationBook] [nvarchar](10) NULL,
	[UseDuplicationList] [tinyint] NULL,
	[ResponsibilityCenter] [nvarchar](10) NULL,
	[CrossReferenceNo] [nvarchar](20) NULL,
	[UnitofMeasureCrossRef] [nvarchar](10) NULL,
	[CrossReferenceType] [int] NULL,
	[CrossReferenceTypeNo] [nvarchar](30) NULL,
	[ItemCategoryCode] [nvarchar](20) NULL,
	[Nonstock] [tinyint] NULL,
	[PurchasingCode] [nvarchar](10) NULL,
	[ProductGroupCode] [nvarchar](10) NULL,
	[ApplFromItemEntry] [int] NULL,
	[ReturnReasonCode] [nvarchar](10) NULL,
	[AllowLineDisc] [tinyint] NULL,
	[CustomerDiscGroup] [nvarchar](20) NULL,
	[TMPGMORG] [nvarchar](50) NULL,
	[TMDateTimeCreated] [datetime] NULL,
	[TMReminder1] [nvarchar](50) NULL,
	[TMReminder2] [nvarchar](50) NULL
) ON [PRIMARY]
GO
