USE [ODS_SERVER]
GO

/****** Object:  Table [dbo].[Sales_Header]    Script Date: 19/07/2025 18:38:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales_Header](
	[DocumentType] [int] NULL,
	[No] [nvarchar](20) NULL,
	[SelltoCustomerNo] [nvarchar](20) NULL,
	[BilltoCustomerNo] [nvarchar](20) NULL,
	[BilltoName] [nvarchar](100) NULL,
	[BilltoName2] [nvarchar](50) NULL,
	[BilltoAddress] [nvarchar](100) NULL,
	[BilltoAddress2] [nvarchar](50) NULL,
	[BilltoCity] [nvarchar](30) NULL,
	[BilltoContact] [nvarchar](100) NULL,
	[YourReference] [nvarchar](35) NULL,
	[ShiptoCode] [nvarchar](10) NULL,
	[ShiptoName] [nvarchar](100) NULL,
	[ShiptoName2] [nvarchar](50) NULL,
	[ShiptoAddress] [nvarchar](100) NULL,
	[ShiptoAddress2] [nvarchar](50) NULL,
	[ShiptoCity] [nvarchar](30) NULL,
	[ShiptoContact] [nvarchar](100) NULL,
	[OrderDate] [datetime] NULL,
	[PostingDate] [datetime] NULL,
	[ShipmentDate] [datetime] NULL,
	[PostingDescription] [nvarchar](100) NULL,
	[PaymentTermsCode] [nvarchar](10) NULL,
	[DueDate] [datetime] NULL,
	[PaymentDiscountPercent] [numeric](38, 20) NULL,
	[PmtDiscountDate] [datetime] NULL,
	[ShipmentMethodCode] [nvarchar](10) NULL,
	[LocationCode] [nvarchar](10) NULL,
	[ShortcutDimension1Code] [nvarchar](20) NULL,
	[ShortcutDimension2Code] [nvarchar](20) NULL,
	[CustomerPostingGroup] [nvarchar](20) NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[CurrencyFactor] [numeric](38, 20) NULL,
	[CustomerPriceGroup] [nvarchar](10) NULL,
	[PricesIncludingVAT] [tinyint] NULL,
	[InvoiceDiscCode] [nvarchar](20) NULL,
	[CustomerDiscGroup] [nvarchar](20) NULL,
	[LanguageCode] [nvarchar](10) NULL,
	[SalespersonCode] [nvarchar](20) NULL,
	[OrderClass] [nvarchar](10) NULL,
	[NoPrinted] [int] NULL,
	[OnHold] [nvarchar](20) NULL,
	[AppliesToDocType] [int] NULL,
	[AppliesToDocNo] [nvarchar](20) NULL,
	[BalAccountNo] [nvarchar](20) NULL,
	[Ship] [tinyint] NULL,
	[Invoice] [tinyint] NULL,
	[PrintPostedDocuments] [tinyint] NULL,
	[ShippingNo] [nvarchar](20) NULL,
	[PostingNo] [nvarchar](20) NULL,
	[LastShippingNo] [nvarchar](20) NULL,
	[LastPostingNo] [nvarchar](20) NULL,
	[PrepaymentNo] [nvarchar](20) NULL,
	[LastPrepaymentNo] [nvarchar](20) NULL,
	[PrepmtCrMemoNo] [nvarchar](20) NULL,
	[LastPrepmtCrMemoNo] [nvarchar](20) NULL,
	[VATRegistrationNo] [nvarchar](20) NULL,
	[CombineShipments] [tinyint] NULL,
	[ReasonCode] [nvarchar](10) NULL,
	[GenBusPostingGroup] [nvarchar](20) NULL,
	[EU3PartyTrade] [tinyint] NULL,
	[TransactionType] [nvarchar](10) NULL,
	[TransportMethod] [nvarchar](10) NULL,
	[VATCountryRegionCode] [nvarchar](10) NULL,
	[SelltoCustomerName] [nvarchar](100) NULL,
	[SelltoCustomerName2] [nvarchar](50) NULL,
	[SelltoAddress] [nvarchar](100) NULL,
	[SelltoAddress2] [nvarchar](50) NULL,
	[SelltoCity] [nvarchar](30) NULL,
	[SelltoContact] [nvarchar](100) NULL,
	[BilltoPostCode] [nvarchar](20) NULL,
	[BilltoCounty] [nvarchar](30) NULL,
	[BilltoCountryRegionCode] [nvarchar](10) NULL,
	[SelltoPostCode] [nvarchar](20) NULL,
	[SelltoCounty] [nvarchar](30) NULL,
	[SelltoCountryRegionCode] [nvarchar](10) NULL,
	[ShiptoPostCode] [nvarchar](20) NULL,
	[ShiptoCounty] [nvarchar](30) NULL,
	[ShiptoCountryRegionCode] [nvarchar](10) NULL,
	[BalAccountType] [int] NULL,
	[ExitPoint] [nvarchar](10) NULL,
	[Correction] [tinyint] NULL,
	[DocumentDate] [datetime] NULL,
	[ExternalDocumentNo] [nvarchar](35) NULL,
	[Area] [nvarchar](10) NULL,
	[TransactionSpecification] [nvarchar](10) NULL,
	[PaymentMethodCode] [nvarchar](10) NULL,
	[ShippingAgentCode] [nvarchar](10) NULL,
	[PackageTrackingNo] [nvarchar](30) NULL,
	[NoSeries] [nvarchar](20) NULL,
	[PostingNoSeries] [nvarchar](20) NULL,
	[ShippingNoSeries] [nvarchar](20) NULL,
	[TaxAreaCode] [nvarchar](20) NULL,
	[TaxLiable] [tinyint] NULL,
	[VATBusPostingGroup] [nvarchar](20) NULL,
	[Reserve] [int] NULL,
	[AppliesToID] [nvarchar](20) NULL,
	[VATBaseDiscountPercent] [numeric](38, 20) NULL,
	[Status] [int] NULL,
	[InvoiceDiscountCalculation] [int] NULL,
	[InvoiceDiscountValue] [numeric](38, 20) NULL,
	[SendICDocument] [tinyint] NULL,
	[ICStatus] [int] NULL,
	[SelltoICPartnerCode] [nvarchar](20) NULL,
	[BilltoICPartnerCode] [nvarchar](20) NULL,
	[ICDirection] [int] NULL,
	[Prepayment] [numeric](38, 20) NULL,
	[PrepaymentNoSeries] [nvarchar](20) NULL,
	[CompressPrepayment] [tinyint] NULL,
	[PrepaymentDueDate] [datetime] NULL,
	[PrepmtCrMemoNoSeries] [nvarchar](20) NULL,
	[PrepmtPostingDescription] [nvarchar](100) NULL,
	[PrepmtPmtDiscountDate] [datetime] NULL,
	[PrepmtPaymentTermsCode] [nvarchar](10) NULL,
	[PrepmtPaymentDiscountPercent] [numeric](38, 20) NULL,
	[QuoteNo] [nvarchar](20) NULL,
	[QuoteValidUntilDate] [datetime] NULL,
	[QuoteSentToCustomer] [tinyint] NULL,
	[QuoteAccepted] [tinyint] NULL,
	[QuoteAcceptedDate] [datetime] NULL,
	[JobQueueStatus] [int] NULL,
	[JobQueueEntryID] [uniqueidentifier] NULL,
	[IncomingDocumentEntryNo] [int] NULL,
	[IsTest] [tinyint] NULL,
	[SelltoPhoneNo] [nvarchar](30) NULL,
	[SelltoEmail] [nvarchar](80) NULL,
	[PaymentInstructionsId] [uniqueidentifier] NULL,
	[WorkDescription] [nvarchar](max) NULL,
	[DimensionSetID] [int] NULL,
	[PaymentServiceSetID] [uniqueidentifier] NULL,
	[DirectDebitMandateID] [nvarchar](35) NULL,
	[DocNoOccurrence] [int] NULL,
	[CampaignNo] [nvarchar](20) NULL,
	[SelltoCustomerTemplateCode] [nvarchar](10) NULL,
	[SelltoContactNo] [nvarchar](20) NULL,
	[BilltoContactNo] [nvarchar](20) NULL,
	[BilltoCustomerTemplateCode] [nvarchar](10) NULL,
	[OpportunityNo] [nvarchar](20) NULL,
	[ResponsibilityCenter] [nvarchar](10) NULL,
	[ShippingAdvice] [int] NULL,
	[PostingFromWhseRef] [int] NULL,
	[RequestedDeliveryDate] [datetime] NULL,
	[PromisedDeliveryDate] [datetime] NULL,
	[ShippingTime] [nvarchar](32) NULL,
	[OutboundWhseHandlingTime] [nvarchar](32) NULL,
	[ShippingAgentServiceCode] [nvarchar](10) NULL,
	[Receive] [tinyint] NULL,
	[ReturnReceiptNo] [nvarchar](20) NULL,
	[ReturnReceiptNoSeries] [nvarchar](20) NULL,
	[LastReturnReceiptNo] [nvarchar](20) NULL,
	[AllowLineDisc] [tinyint] NULL,
	[GetShipmentUsed] [tinyint] NULL,
	[Id] [uniqueidentifier] NULL,
	[AssignedUserID] [nvarchar](50) NULL,
	[systemId] [uniqueidentifier] NULL,
	[ACY Created By] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
